project:
  type: website
  output-dir: docs

website:
  title: "Quarto website template"
  site-url: "https://kuan-liu.github.io/"
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Kuan Liu, University of Toronto @ 2022"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - text: "CV"
        href: file/Kuan_Latex_CV.pdf
      - icon: github
        href: https://github.com/Kuan-Liu
      - icon: twitter
        href: https://twitter.com/KuanLiu2

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true

editor: visual

freeze: auto


        
